Controllers films users
jager8meister/java-filmorate pull request #1
Opened 2022-09-06 23:52 UTC by jager8meister

to pull

2022-09-10 16:27 UTC, jager8meister commented
18 version

2022-09-18 15:31 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев, жду новую итерацию работы.

2022-09-18 15:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    @PostMapping()
Пустые скобки не нужны

2022-09-18 15:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public @ResponseBody ResponseEntity<Film> addFilm(@RequestBody Film film) throws ValidationException {
Вообще спринг сам умеет обьекты сериализовать/десериализовать и можно не оборачивать в ResponseEntity, лишние действия скажем так

2022-09-18 15:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Slf4j
Зачем тут эта аннотация? Она явно лишняя

2022-09-18 15:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Integer id;
В качестве идентификатора лучше использовать Long чтобы проблема переполнения была максимально нереальна

2022-09-18 15:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Slf4j
Аналогично, лишняя аннотация и идентификатор лучше Long использовать

2022-09-18 15:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Для улучшения валидации, можно воспользоваться зависимостью
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-validation</artifactId>
</dependency>
2. В данном случае на поля класса модели можно повесить дополнительные аннотации, например,
@NotNull к полю для проверки на null, @NotBlank — для проверки на пустую строку, @Email/Pattern — для проверки на соответствие формату электронного адреса.

2022-09-18 15:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private User checkName(User user) {
Вы вроде делаете специальные классы для валидации, по этому, кажется, логичнее перенести туда этот метод

2022-09-18 15:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +public class UserController {
Давайте для контроллеров напишем unit тесты и проверим работоспособность приложения на граничных условиях валидации. Свой код лучше тестировать

2022-09-30 15:52 UTC, Frilock requested changes
В целом все ок, но есть 1 сомнительное место, посмотрите и присылайте повторно

2022-09-30 15:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validators/UserValidator.java
> +    private static boolean checkDOB(User user) {
А что за DOB? Мб лучше как то по другому назвать?

2022-09-30 15:52 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validators/FilmValidator.java
> +        if (film.getReleaseDate().isAfter(checkDate))
Вам нужно проверять, что эти поля заполнены film.getReleaseDate() и film.getDescription() и т.д., поскольку если там будет null, то вы получите NPE

2022-10-02 17:28 UTC, Frilock approved these changes
Принято

2022-10-02 17:28 UTC, Frilock commented on .gitignore
> +!src/main/**/target/
Коммиты лучше объединять, а то когда их так много это не хорошо

2022-10-02 20:41 UTC, merged