add-friends-likes
jager8meister/java-filmorate pull request #2
Opened 2022-11-30 22:01 UTC by jager8meister

2022-12-01 06:35 UTC, Frilock requested changes
Добрый день, посмотрел работу:
1. Не до конца разобрались с работой bean (бинов) в Spring, это важный момент, стоит ему уделить особое внимание.
2. Работу с частью аннотаций и с ResponseEntity лучше перенести в контроллер
3. Мелкие комментарии по коду
4. Почему отсутствуют тесты на функционал? Надо бы их добавить

2022-12-01 06:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private FilmService service = new FilmService();
Смотрите, не до конца разобрались с использованием бинов в программе. Ваш FilmService помечен аннотацией Service, что говорит спрингу, что данный класс является бином и компонентом спринга. Такие зависимости нужно инжектить в приложение с помощью Autowired. Нужно разобраться Вам поподробнее с этой темой

2022-12-01 06:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +    public @ResponseBody ResponseEntity<Film> addFilm(@Valid @RequestBody Film film) {
@ResponseBody - это лишнее. Данную аннотацию нужно использовать в контроллере, в общем то как и @RequestBody

2022-12-01 06:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +        return new ResponseEntity<>(film, HttpStatus.BAD_REQUEST);
Лучше оборачивать в ResponseEntity в контролере, а в сервисе работать с обычным обьектом.

2022-12-01 06:35 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storages/InMemoryFilmStorage.java
> +        throw new StorageException("Invalid film.");
Эту строчку лучше в catch засунуть

2022-12-03 09:41 UTC, Frilock requested changes
Добрый день, оставил еще пару комментариев к работе.

2022-12-03 09:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/comparator/FilmComparator.java
> +package ru.yandex.practicum.filmorate.comparator;
На мой взгляд пакет лучше назвать utils или что то такое

2022-12-03 09:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND );
пробел лишний после NOT_FOUND

2022-12-03 09:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        } catch (StorageException e) {
Вообще мне кажется, что стоит ловить любое исключение - Exception e, поскольку пользователю все равно нужно отдать ошибку, если она произошла. 
Кроме того, как задание со звездочкой из ТЗ пункт:
НастройтеExceptionHandler для централизованной обработки ошибок. https://struchkov.dev/blog/exception-handling-controlleradvice/

2022-12-03 09:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Component
Не разобрались до конца. Component нужно вешать на классы, которые вы хотите сделать бином спринга. На классы модели вешать такие аннотации не нужно

2022-12-03 09:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +    public HttpStatus addFilm(Film film) {
Мне кажется, что в методах add и update тоже нужно возвращать либо void либо что то еще, работа со HttpStatus это прерогатива контроллера. То есть логика такая - если ошибка была, то нужно ее пользователю показать, если ошибки не было значит - HttpStatus.Ok. То есть тут явно прокидывать этот статус не нужно

2022-12-03 09:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +    private InMemoryFilmStorage inMemoryFilmStorage;
Смотрите правильным решением будет "инжектить" интерфейс, а не его реализацию. То есть, нужно делать так:
private FilmStorage filmStorage; 
А спринг сам заинжектит его реализацию - InMemoryFilmStorage.

2022-12-03 09:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +    InMemoryUserStorage inMemoryUserStorage;
Модификатор забыли

2022-12-03 09:41 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	UserController userController;
Модификаторы

2022-12-04 11:30 UTC, Frilock requested changes
Добрый день, в целом уже хорошо, еще пару мест не поправили. Если что то не хотите править, или с чем то не согласны, вы можете на мои комментарии на github отвечать просто. А те что поправили закрывать. Или писать ответ, мол, поправил. Так проще взаимодействовать. Если совсем что то не ясно, можете написать мне или наставнику.

2022-12-04 11:30 UTC, Frilock commented on pom.xml
> +			<version>5.3.24</version>
Версии библиотек правильнее указывать в одном месте, а именно, в properties, чтобы при смене версии не приходилось лазить по иногда большому pom файлу.

2022-12-04 11:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private FilmService service;
Когда присваивание происходит 1 раз, можно использовать модификатор final. По идее вам IDEA должна подсказывать такие моменты

2022-12-04 11:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public ResponseEntity<String> handleException(RuntimeException exception) {
Вообще лучше отдельный FilmorateErrorHandler сделать (с аннотацией RestControllerAdvice , как то так, скидывал статью, там более подробно), куда вынести вот этот код из ваших контроллеров

2022-12-04 11:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private String name;
Мне кажется name тоже должно валидироваться

2022-12-04 11:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +    InMemoryUserStorage inMemoryUserStorage;
Не добавили модифкатор

2022-12-04 11:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storages/InMemoryUserStorage.java
> +    private Map<Long, User> userMap = new HashMap<>();
Тоже можно final

2022-12-04 11:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +    private InMemoryFilmStorage inMemoryFilmStorage;
Я так понимаю, инжектите тут реализацию, поскольку в интерфейсе не хватает методов. Вообще методы туда добавить можно, которых не хватает

2022-12-04 21:38 UTC, jager8meister commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private String name;
оно валидируется методом checkName() в классе UserValidator.

2022-12-06 06:57 UTC, Frilock approved these changes
Вадим, работу принимаю, но все равно опять же есть нюансы. Давайте при работе над следующей задачей, вы поправите и эти моменты.

2022-12-06 06:57 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/handlers/FilmOrRateExceptionHandler.java
> +    @ExceptionHandler(RuntimeException.class)
Тут вообще нужно более детальные исключения ловить. То есть у Вас в коде бросается где то FilmorateNotFoundException - вы тут ловите его и отдаете пользователю статус NotFound и соответствующий код и сообщение.
В другом месте у Вас какое то другое исключение, например, FilmorateUserExistException - вы ловите его и отдаете пользователю другой код и другой статус...

2022-12-06 06:57 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +    private UserStorage inMemoryUserStorage;
Тоже можно final

2022-12-06 15:54 UTC, merged