Add database
jager8meister/java-filmorate pull request #3
Opened 2022-12-13 09:49 UTC by jager8meister

2022-12-13 18:18 UTC, Frilock requested changes
Добрый вечер, честно говоря работа не соответствует Java Code Style, все таки уже не первую работу сдаете и требования должны знать, пожалуйста, приведите работу к требуемому виду. Кроме того, проверьте наличие лишних аннотаций в работе.

2022-12-13 18:18 UTC, Frilock commented on pom.xml
> +			<version>2.7.6</version>
Вроде бы с вами обсуждали тему, что лучше номера версий выносить в properties

2022-12-13 18:18 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenreController.java
> +    @GetMapping()
Пустые скобки не нужны

2022-12-13 18:18 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenreController.java
> +
Лишняя пустая строчка

2022-12-13 18:18 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenreController.java
> +@Slf4j
Аннотацию для логгера вижу, а логирования не вижу

2022-12-13 18:18 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MpaController.java
> +@Slf4j
Аннотация стоит, а логирования нет

2022-12-13 18:18 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            if (user.getId() == null)
if конструкции нужно обособлять во избежание ошибок по невнимательности

2022-12-13 18:18 UTC, Frilock commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS usersBase(
Предлагаю между разными CREATE пропускать одну строчку, чтобы не сливалось

2022-12-13 18:18 UTC, Frilock commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS filmsBase(
Честно говоря не очень нравиться добавление Base на конце, кроме того при именовании таблиц принято разделять слова с помощью нижнего подчеркивания, но все равно идея добавления Base на конце как то не очень

2022-12-13 18:18 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	public void testFindUserById() {
Хотелось бы также увидеть негативные тесты, где в методах были бы брошены ошибки 
(можно использовать assertThrows)

2022-12-13 18:18 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/utils/GenreComparator.java
> +    public int compare(Genre o1, Genre o2) {
А почему такой неочевидный compare, зачем возвращать разницу идентификаторов?

2022-12-13 18:18 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storages/InMemoryUserStorage.java
> -public class InMemoryUserStorage implements UserStorage {
я думаю что пока нет смысла удалять эти классы, поскольку логику тут в том, чтобы вы научились работать с Qualifaer аннотацией

2022-12-13 18:18 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/MpaService.java
> +        if (id < 1 || id > 5)
Пожалуйста обособляйте конструкции if, else и т.д. Это хорошая практика

2022-12-13 18:18 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/MpaService.java
> +        Mpa res = new Mpa();
Пожалуйста не сокращайте названия переменных, это не особо принято

2022-12-13 18:18 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/MpaService.java
> +@Slf4j
Опять же аннотация висит, а логирования не видно

2022-12-13 18:18 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public Map<String, Object> toMap() {
Между методами и переменными пропускайте 1 строчку пожалуйста

2022-12-14 14:31 UTC, Frilock requested changes
Добрый вечер, оставил еще ряд комментариев

2022-12-14 14:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenreController.java
> +            log.error("Invalid genre id");
Еще лучше тогда добавлять какой id

2022-12-14 14:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        List<Map<String, Object>> res = jdbcTemplate.queryForList(selectFromFilms );
Лишний пробел перед )

2022-12-14 14:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            if (elem.get("film_name").equals(film.getName()) &&
У вас эта проверка дублируется как минимум в нескольких местах, вынесите в отдельный метод эту проверку и вызывайте где вам нужно, кстати если в БД есть такая запись вам база исключение кинет

2022-12-14 14:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +                if (genre.getName() == null)
Вроде писал к вам просьбу обособлять такие конструкции...Мы же не на питоне пишем

2022-12-14 14:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public static List<Genre> getAllFilmGenres(List<Map<String, Object>> raw) {
А точно публичный? а почему тогда в интерфейсе нет?

2022-12-14 14:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +                    "name", "birthday")
На прошлую строчку аргументы нормально влезают

2022-12-14 14:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        user.setBirthday(LocalDate.parse(elem.get("BIRTHDAY").toString()));
А elem.get("BIRTHDAY") null не вернет?

2022-12-14 14:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/GenreService.java
> +        if (id < 1 || id > 6)
А почему от 1 до 6? Магические числа оставлять не особо принятая практика, вынесите их в константу чтобы по ней было ясно что они значат

2022-12-15 07:28 UTC, jager8meister commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        user.setBirthday(LocalDate.parse(elem.get("BIRTHDAY").toString()));
нет не вернет, так как пользователя без даты рождения невозможно добавить в бд, он не пройдет валидацию, а конкретней метод checkBirthday().

2022-12-15 20:16 UTC, Frilock approved these changes
Принято

2022-12-16 07:22 UTC, merged